###########
# site.title, site.url, site.author.name

title:  'autotitulado'
author:
name: 'David Irigoin'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
#path:  / 
url:  'http://irigoin.ar/'
paginate: 2

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md

permalink:  "/:title"

lsi: false

# Gems
gems: [jekyll-paginate]
